### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by euhruska** [dsrahul30/Christofides#3]
when running on a small problem I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/Christofides/christofides.py", line 164, in compute
  File "build/bdist.macosx-10.9-x86_64/egg/Christofides/christofides.py", line 120, in Euler_Tour
UnboundLocalError: local variable 'edge' referenced before assignment
```
I looks like the lines 120-123 in Christofides/christofides.py are wrongly indented with the for loop, maybe they should be indented with if command above.

**Comment by dsrahul30** [comment]
Thanks for the information! Looking into it.

**Comment by gagangoku** [comment]
Its a bug. Its not working even for the test cases mentioned in graph.py

**Comment by alfcar9** [comment]
SimonDeRidde has a pull request that works on that repository and fixes the bug.
